version: '3.7'

services:
  service1:
    build: ./service1
    command: npm start
    working_dir: /usr/src/server
    ports:
      - "8001:80"
  service2:
    build: ./service2
    command: npm start
    working_dir: /usr/src/server



